name: socialsnob
favicon: null
layout_spectrum: 0.51081
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#adadad'
    - '#6e6e6e'
    - '#4d4d4d'
    - '#333333'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
