purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.797491
  brandStrength: 0
  lightness: 0.281362
  brandColors: []
  rhythmicContrast: 0.7419355
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: socialsnob
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5
layout_spectrum: 1
