name: socialsnob
favicon: null
layout_spectrum: 0.51081
typography_spectrum: 0.26486
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d6d6d6'
    - '#b5b5b5'
    - '#4a4a4a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
